### ISSUE TITLE
Change default ConsumerConfig or ProducerConfig

### ISSUE THREAD

**Issue by akrystian** [DDTH/ddth-kafka#4]
Hi,

Is there possible way to set custom ConsumerConfig or ProducerConfig (eg. HEARTBEAT_INTERVAL_MS_CONFIG)? 

Thanks

**Comment by btnguyen2k** [comment]
Hi @akrystian,

Yes it is possible since v1.2.1+ (which will be available on Maven next couple of hours).

Cheers,

**Comment by akrystian** [comment]
Hi,

Very fast reaction. :+1: 
We'll try it out.

Thanks,
