### ISSUE TITLE
osgi Bundle activator

### ISSUE THREAD

**Issue by MarcoFierimonte** [DDTH/ddth-kafka#5]
Hi btnguyen2k,

how can I implement  BundleActivator class in your ddth-kafka bundle? Do I need to import org.osgi.core libraries? 

Thanks.
Marco

**Comment by btnguyen2k** [comment]
Hi @MarcoFierimonte,

Sample of (simple) steps:
- You create your own bundle, that imports ddth-kafka.
- Implement BundleActivator class in your bundle and initialize needed objects (eg. KafkaClient).

For quick OSGi Bundle testing, you can drop your bundle(s) into a simple OSGi server (https://github.com/DDTH/osgiserver) and see if everything works well.

Regards,
Thanh Nguyen
